In [8]:
import sys
import os
import pandas as pd
import numpy as np

sys.path.append(os.path.abspath('src'))

from src.config import SIM_CONFIG
from src.users import generate_users
from src.sessions import generate_sessions
from src.events import generate_events
from src.orders import generate_orders
from src.order_items import generate_order_items

rng = np.random.default_rng(seed=42)
print("Setup complete! Modules loaded successfully.")

Setup complete! Modules loaded successfully.

In [4]:
test_users_df = generate_users(total_users=5, rng=rng)
display(test_users_df)

Generating 5 users
users tables generated!

,user_id,account_created_at,city,region,user_tenure_days,latent_income_score,latent_digital_literacy,latent_trust_in_platform
0,019ed93587df7850afde718e358a9c75,2023-11-28 03:23:38,Quezon City,NCR,32,-1.302180,0.370798,0.213856
1,019ed93587df7850afde719afde66d27,2023-03-23 21:56:15,Makati,NCR,282,0.127840,0.926765,0.323986
2,019ed93587df7850afde71a620372542,2023-05-06 07:15:48,Cavite,Region IV-A,238,-0.316243,0.643865,0.272065
3,019ed93587df7850afde71bbfd34aab7,2023-07-23 19:09:54,Manila,NCR,160,-0.016801,0.822762,0.278443
4,019ed93587df7850afde71c39591d8fe,2023-07-25 21:44:24,Cebu City,Region VII,158,-0.853044,0.443414,0.276947

In [5]:
test_sessions_df = generate_sessions(df_users=test_users_df, rng=rng)
display(test_sessions_df)

Generating 8 sessions
sessions table generated!

,session_id,user_id,session_number,acquisition_channel,session_start_time,session_date,is_weekend,session_duration_seconds,device_os_version,device_group
0,019ed93c9de376129ba244e7b30785be,019ed93587df7850afde718e358a9c75,1,TikTok,2023-11-29 23:57:59,2023-11-29,False,869,iOS 17.3,Mobile
1,019ed93c9de376129ba244f6687f8479,019ed93587df7850afde718e358a9c75,2,Facebook,2023-11-28 16:33:08,2023-11-28,False,558,Android 14,Mobile
2,019ed93c9de376129ba2450425c6c21e,019ed93587df7850afde718e358a9c75,3,Organic,2023-11-29 01:01:10,2023-11-29,False,279,iOS 17.3,Mobile
3,019ed93c9de376129ba2451f5c5f9796,019ed93587df7850afde719afde66d27,1,TikTok,2023-03-30 10:37:41,2023-03-30,False,416,Windows 11,Desktop
4,019ed93c9de376129ba2452f0d5e630c,019ed93587df7850afde71a620372542,1,Facebook,2023-06-30 04:43:12,2023-06-27,False,121,Android 13,Mobile
5,019ed93c9de376129ba24533f86807cf,019ed93587df7850afde71bbfd34aab7,1,Facebook,2023-09-30 07:30:11,2023-09-27,False,196,iOS 17.3,Mobile
6,019ed93c9de376129ba2454417699b37,019ed93587df7850afde71bbfd34aab7,2,Facebook,2023-08-03 07:48:07,2023-08-03,False,10,Android 12,Mobile
7,019ed93c9de376129ba2455ac4943393,019ed93587df7850afde71c39591d8fe,1,Organic,2023-08-03 18:21:29,2023-08-03,False,10,iOS 17.3,Mobile

In [6]:
test_events_df = generate_events(df_sessions=test_sessions_df, df_users=test_users_df, rng=rng, n_workers=1)
display(test_events_df)

Generating events for 8 sessions

,event_id,session_id,event_timestamp,event_type,viewed_category,android_error
0,019ed93c-eab8-7160-8916-d315fb5df40b,019ed93c9de376129ba244e7b30785be,2023-11-29 23:57:59,view_item,Apparel,NaN
1,019ed93c-eab8-7160-8916-d32ff1056941,019ed93c9de376129ba244e7b30785be,2023-11-30 00:00:41,view_item,Apparel,NaN
2,019ed93c-eab8-7160-8916-d3395a45b1f7,019ed93c9de376129ba244e7b30785be,2023-11-30 00:01:10,view_item,Apparel,NaN
3,019ed93c-eab8-7160-8916-d345b37518ee,019ed93c9de376129ba244e7b30785be,2023-11-30 00:01:33,add_to_cart,Apparel,NaN
4,019ed93c-eab8-7160-8916-d35934fde2d3,019ed93c9de376129ba244e7b30785be,2023-11-30 00:01:47,begin_checkout,NaN,NaN
5,019ed93c-eab8-7160-8916-d363087c9f6b,019ed93c9de376129ba244e7b30785be,2023-11-30 00:02:34,purchase,NaN,NaN
6,019ed93c-eab8-7160-8916-d371fad1e6ec,019ed93c9de376129ba244f6687f8479,2023-11-28 16:33:08,view_item,Apparel,NaN
7,019ed93c-eab8-7160-8916-d383f544311a,019ed93c9de376129ba244f6687f8479,2023-11-28 16:33:28,view_item,Home Goods,NaN
8,019ed93c-eab8-7160-8916-d39a1771ac55,019ed93c9de376129ba244f6687f8479,2023-11-28 16:34:08,view_item,Apparel,NaN
9,019ed93c-eab8-7160-8916-d3a7371a09ca,019ed93c9de376129ba244f6687f8479,2023-11-28 16:34:30,add_to_cart,Apparel,NaN
10,019ed93c-eab8-7160-8916-d3b7fbb65d0b,019ed93c9de376129ba2450425c6c21e,2023-11-29 01:01:10,view_item,Consumables,NaN
11,019ed93c-eab8-7160-8916-d3c66ae58341,019ed93c9de376129ba2450425c6c21e,2023-11-29 01:01:26,add_to_cart,Consumables,NaN
12,019ed93c-eab8-7160-8916-d3d4fda5d6e8,019ed93c9de376129ba2450425c6c21e,2023-11-29 01:01:31,view_item,Apparel,NaN
13,019ed93c-eab8-7160-8916-d3ebc7589dfb,019ed93c9de376129ba2451f5c5f9796,2023-03-30 10:37:41,view_item,Consumables,NaN
14,019ed93c-eab8-7160-8916-d3ff66801c21,019ed93c9de376129ba2451f5c5f9796,2023-03-30 10:38:13,add_to_cart,Consumables,NaN
15,019ed93c-eab8-7160-8916-d4020b2380e5,019ed93c9de376129ba2451f5c5f9796,2023-03-30 10:38:32,begin_checkout,NaN,NaN
16,019ed93c-eab8-7160-8916-d41846785c57,019ed93c9de376129ba2452f0d5e630c,2023-06-30 04:43:12,view_item,Consumables,NaN
17,019ed93c-eab8-7160-8916-d4219ff45693,019ed93c9de376129ba2452f0d5e630c,2023-06-30 04:43:43,view_item,Apparel,NaN
18,019ed93c-eab8-7160-8916-d430f692647f,019ed93c9de376129ba2452f0d5e630c,2023-06-30 04:45:13,drop_off,Apparel,ERR_SESSION_TIMEOUT
19,019ed93c-eab8-7160-8916-d44c4b232609,019ed93c9de376129ba24533f86807cf,2023-09-30 07:30:11,view_item,Apparel,NaN
20,019ed93c-eab9-7fa3-93ba-34e02a27baeb,019ed93c9de376129ba24533f86807cf,2023-09-30 07:31:13,add_to_cart,Apparel,NaN
21,019ed93c-eab9-7fa3-93ba-34fbc8964b68,019ed93c9de376129ba24533f86807cf,2023-09-30 07:31:13,view_item,Apparel,NaN
22,019ed93c-eab9-7fa3-93ba-35003445252f,019ed93c9de376129ba24533f86807cf,2023-09-30 07:31:16,add_to_cart,Apparel,NaN
23,019ed93c-eab9-7fa3-93ba-3518272b6b4c,019ed93c9de376129ba24533f86807cf,2023-09-30 07:32:42,begin_checkout,NaN,NaN
24,019ed93c-eab9-7fa3-93ba-352cc27c8f11,019ed93c9de376129ba2454417699b37,2023-08-03 07:48:07,view_item,Home Goods,NaN
25,019ed93c-eab9-7fa3-93ba-3535f10e9b61,019ed93c9de376129ba2454417699b37,2023-08-03 07:48:14,view_item,Apparel,NaN
26,019ed93c-eab9-7fa3-93ba-35434282755e,019ed93c9de376129ba2454417699b37,2023-08-03 07:48:17,drop_off,Apparel,ERR_SESSION_TIMEOUT
27,019ed93c-eab9-7fa3-93ba-355368069aff,019ed93c9de376129ba2455ac4943393,2023-08-03 18:21:29,view_item,Consumables,NaN

In [9]:
test_orders_df = generate_orders(df_events=test_events_df, df_sessions=test_sessions_df, rng=rng)
test_order_items_df = generate_order_items(df_orders=test_orders_df, df_users=test_users_df, rng=rng)

display(test_orders_df.head())
display(test_order_items_df.head())

Generating 1 orders for purchases events
Generating order items for 1 orders
order items table generated!

,order_id,session_id,user_id,order_timestamp,payment_methods
0,019ed940b2847960b58949e42de4a595,019ed93c9de376129ba244e7b30785be,019ed93587df7850afde718e358a9c75,2023-11-30 00:02:34,Credit Card

,order_item_id,order_id,product_category,item_price,quantity,discount_percentage
0,019ed940b2877653a4b91657df24f0a7,019ed940b2847960b58949e42de4a595,Electronics,112.62,2,0.5