In [32]:
import sys
import os
import pandas as pd
import numpy as np

sys.path.append(os.path.abspath('src'))

from src.config import SIM_CONFIG
from src.users import generate_users
from src.sessions import generate_sessions
from src.events import generate_events
from src.orders import generate_orders
from src.order_items import generate_order_items

rng = np.random.default_rng(seed=42)
print("Setup complete! Modules loaded successfully.")

Setup complete! Modules loaded successfully.

In [33]:
test_users_df = generate_users(total_users=1000000, rng=rng)
display(test_users_df.head())

Generating 1000000 users
users tables generated!

,user_id,account_created_at,city,region,user_tenure_days,latent_income_score,latent_digital_literacy,latent_trust_in_platform
0,019ee0c2a37975b1838cc894095ec85b,2023-11-28 04:21:20,Davao del Norte,Region XI,32,0.334835,0.039387,0.498106
1,019ee0c2a37975b1838cc8abee503eeb,2023-03-23 15:20:48,Cebu,Region VII,282,0.078654,0.700104,0.049789
2,019ee0c2a37975b1838cc8b4c0556110,2023-05-06 06:09:19,Siquijor,NIR,238,0.836328,0.424339,0.271859
3,019ee0c2a37975b1838cc8ce308a94ee,2023-07-23 22:47:29,Makati,NCR,160,0.999611,0.141295,0.104224
4,019ee0c2a37975b1838cc8d85df62f1d,2023-07-25 08:38:11,Cavite,Region IV-A,158,1.000962,0.595593,0.166513

In [34]:
test_sessions_df = generate_sessions(df_users=test_users_df, rng=rng)
display(test_sessions_df.head())

Generating 1900888 sessions
sessions table generated!

,session_id,user_id,session_number,acq_channel,session_start_time,session_date,is_weekend,session_duration_seconds,device_os_version,device_group
0,019ee0c2f0bb79b1ae276a19f53fc00e,019ee0c2a37975b1838cc894095ec85b,1,Facebook,2023-12-03 17:27:38,2023-12-03,True,88,macOS Monterey,Desktop
1,019ee0c2f0bb79b1ae276a2122142af6,019ee0c2a37975b1838cc8abee503eeb,1,Organic,2023-03-24 05:00:56,2023-03-24,False,125,Android 14,Mobile
2,019ee0c2f0bb79b1ae276a34ffd3eb31,019ee0c2a37975b1838cc8b4c0556110,1,Organic,2023-11-15 18:00:37,2023-11-15,False,58,Windows 11,Desktop
3,019ee0c2f0bb79b1ae276a40d959fa65,019ee0c2a37975b1838cc8ce308a94ee,1,Organic,2023-08-01 13:06:43,2023-08-01,False,144,Android 14,Mobile
4,019ee0c2f0bb79b1ae276a5c9041ab9c,019ee0c2a37975b1838cc8ce308a94ee,2,TikTok,2023-07-24 11:51:43,2023-07-24,False,100,Android 12,Mobile

In [35]:
test_events_df = generate_events(df_sessions=test_sessions_df, df_users=test_users_df, rng=rng, n_workers=1)
display(test_events_df.head())

Generating events for 1900888 sessions

,event_id,session_id,event_timestamp,event_type,viewed_category,android_error
0,019ee0c3-e3a6-7610-bc43-351357d2b040,019ee0c2f0bb79b1ae276a19f53fc00e,2023-12-03 17:27:38,view_item,Fashion,NaN
1,019ee0c3-e3a6-7610-bc43-352b9da8e065,019ee0c2f0bb79b1ae276a19f53fc00e,2023-12-03 17:27:41,view_item_list,Fashion,NaN
2,019ee0c3-e3a6-7610-bc43-353ad8af1400,019ee0c2f0bb79b1ae276a19f53fc00e,2023-12-03 17:28:22,select_item,Fashion,NaN
3,019ee0c3-e3a6-7610-bc43-35460440e4c5,019ee0c2f0bb79b1ae276a19f53fc00e,2023-12-03 17:28:25,view_item,Food and beverages,NaN
4,019ee0c3-e3a6-7610-bc43-355a23ce296f,019ee0c2f0bb79b1ae276a19f53fc00e,2023-12-03 17:29:06,drop_off,Food and beverages,ERR_SESSION_TIMEOUT

In [36]:
test_orders_df = generate_orders(df_events=test_events_df, df_sessions=test_sessions_df, rng=rng)
display(test_orders_df.head())

Generating 59913 orders for purchases events

,order_id,session_id,user_id,order_timestamp,payment_methods
0,019ee0c550f17340a6f01a0a309fd993,019ee0c2f0bb79b1ae276a40d959fa65,019ee0c2a37975b1838cc8ce308a94ee,2023-08-01 13:08:12,Digital Wallet
1,019ee0c550f17340a6f01a10e38e972c,019ee0c2f0bb79b1ae276a64dfa4d92a,019ee0c2a37975b1838cc8ce308a94ee,2023-07-30 19:15:40,Buy Now Pay Later
2,019ee0c550f17340a6f01a207464da12,019ee0c2f0bb79b1ae276a9fd85f9e0c,019ee0c2a37975b1838cc8d85df62f1d,2023-07-31 06:34:32,Digital Wallet
3,019ee0c550f17340a6f01a387c59320b,019ee0c2f0bb79b1ae276e7b86a390a4,019ee0c2a37975b1838ccaa06d7431f3,2023-06-14 22:44:13,Debit Card
4,019ee0c550f17340a6f01a47f25b683c,019ee0c2f0bb79b1ae276f86438e7407,019ee0c2a37975b1838ccb03e125eb55,2023-09-28 07:47:05,COD

In [37]:
test_order_items_df = generate_order_items(df_orders=test_orders_df, df_users=test_users_df, rng=rng)
display(test_order_items_df.head())

Generating order items for 59913 orders
order items table generated!

,order_item_id,order_id,product_category,item_price,quantity,discount_percentage
0,019ee0c552757c019d856c9bc13682b8,019ee0c550f17340a6f01a0a309fd993,Food and beverages,99.99,1,0.0
1,019ee0c552757c019d856ca79e9551c5,019ee0c550f17340a6f01a0a309fd993,Fashion,54.99,1,0.0
2,019ee0c552757c019d856cbd5b8a6ba7,019ee0c550f17340a6f01a10e38e972c,Food and beverages,119.99,1,0.0
3,019ee0c552757c019d856cc12125945f,019ee0c550f17340a6f01a207464da12,Beauty and personal care products,263.99,1,0.0
4,019ee0c552757c019d856cd8f3c6fdeb,019ee0c550f17340a6f01a207464da12,Food and beverages,106.99,1,0.0