In [1]:
import sys
import os
import pandas as pd
import numpy as np

sys.path.append(os.path.abspath('src'))

from src.config import SIM_CONFIG
from src.users import generate_users
from src.sessions import generate_sessions
from src.events import generate_events
from src.orders import generate_orders
from src.order_items import generate_order_items

rng = np.random.default_rng(seed=42)
print("Setup complete! Modules loaded successfully.")

Setup complete! Modules loaded successfully.

In [2]:
test_users_df = generate_users(total_users=10000, rng=rng)
display(test_users_df)

Generating 10000 users
users tables generated!

,user_id,account_created_at,city,region,user_tenure_days,latent_income_score,latent_digital_literacy,latent_trust_in_platform
0,019ede42fec97af19e154fd0b61faaf2,2023-11-28 15:52:17,Davao del Sur,Region XI,32,0.152083,0.315676,0.306382
1,019ede42fec97af19e154fe79e3d52a3,2023-03-23 18:45:52,Batangas,Region IV-A,282,3.097136,0.168668,0.100950
2,019ede42fec97af19e154ff4d97495a9,2023-05-06 11:30:43,Bohol,Region VII,238,3.263254,0.007508,0.182648
3,019ede42fec97af19e15500c973a3e66,2023-07-23 08:05:24,Misamis Occidental,Region X,160,0.622279,0.121608,0.276536
4,019ede42fec97af19e1550121a9c2048,2023-07-25 17:43:34,Nueva Vizcaya,Region II,158,1.684175,0.750866,0.657255
...,...,...,...,...,...,...,...,...
9995,019ede42feca7ef29d7600945db2354a,2023-07-12 20:01:55,Isabela,Region II,171,1.266856,0.501726,0.478650
9996,019ede42feca7ef29d7600a8b79bf4f6,2023-01-01 20:05:19,Iloilo,Region VI,363,2.049366,0.380303,0.657074
9997,019ede42feca7ef29d7600baee7eb9ad,2023-08-24 15:02:18,Tarlac,Region III,128,0.495058,0.539956,0.119799
9998,019ede42feca7ef29d7600cfb4b5f1a5,2023-06-07 15:26:15,Nueva Ecija,Region III,206,1.955054,0.925022,0.099227
9999,019ede42feca7ef29d7600d741d0ca3a,2023-05-20 12:27:30,Negros Occidental,NIR,224,3.929057,0.438529,0.634093

In [3]:
test_sessions_df = generate_sessions(df_users=test_users_df, rng=rng)
display(test_sessions_df)

Generating 19160 sessions
sessions table generated!

,session_id,user_id,session_number,acq_channel,session_start_time,session_date,is_weekend,session_duration_seconds,device_os_version,device_group
0,019ede4306d27b109528dcd6b5ec6741,019ede42fec97af19e154fd0b61faaf2,1,TikTok,2023-12-01 05:02:02,2023-12-01,False,998,Windows 11,Desktop
1,019ede4306d27b109528dced4ddb9908,019ede42fec97af19e154fe79e3d52a3,1,TikTok,2023-03-26 16:42:40,2023-03-26,True,122,Windows 11,Desktop
2,019ede4306d27b109528dcf36c5579dc,019ede42fec97af19e154ff4d97495a9,1,Facebook,2023-05-11 00:14:25,2023-05-11,False,713,macOS Monterey,Desktop
3,019ede4306d27b109528dd0f2a175590,019ede42fec97af19e154ff4d97495a9,2,Organic,2023-05-07 00:53:53,2023-05-07,True,165,macOS Sonoma,Desktop
4,019ede4306d27b109528dd11a283cd9c,019ede42fec97af19e154ff4d97495a9,3,Organic,2023-05-10 08:55:37,2023-05-10,False,318,iOS 17.3,Mobile
...,...,...,...,...,...,...,...,...,...,...
19155,019ede4306d57a138471029e008d484c,019ede42feca7ef29d7600d741d0ca3a,4,Organic,2023-05-26 00:21:56,2023-05-26,False,431,Windows 11,Desktop
19156,019ede4306d57a13847102ae82305c8c,019ede42feca7ef29d7600d741d0ca3a,5,TikTok,2023-05-24 02:47:30,2023-05-24,False,378,Android 14,Mobile
19157,019ede4306d57a13847102b09d06885a,019ede42feca7ef29d7600d741d0ca3a,6,Organic,2023-05-27 02:52:31,2023-05-27,True,10,iOS 16.5,Mobile
19158,019ede4306d57a13847102cf3e27fcf8,019ede42feca7ef29d7600d741d0ca3a,7,Direct,2023-05-24 08:03:19,2023-05-24,False,10,iOS 17.3,Mobile
19159,019ede4306d57a13847102d1a5586f1d,019ede42feca7ef29d7600d741d0ca3a,8,Direct,2023-05-21 10:40:33,2023-05-21,True,149,Android 13,Mobile

In [4]:
test_events_df = generate_events(df_sessions=test_sessions_df, df_users=test_users_df, rng=rng, n_workers=1)
display(test_events_df)

Generating events for 19160 sessions

,event_id,session_id,event_timestamp,event_type,viewed_category,android_error
0,019ede3d-c48e-7eb2-9513-eb25b0276ea8,019ede3dc26074528245beeb5ec8eed9,2023-12-01 05:02:02,view_item,Apparel,NaN
1,019ede3d-c48e-7eb2-9513-eb360d5e5e73,019ede3dc26074528245beeb5ec8eed9,2023-12-01 05:02:16,view_item,Home Goods,NaN
2,019ede3d-c48e-7eb2-9513-eb43c4673bf5,019ede3dc26074528245beeb5ec8eed9,2023-12-01 05:02:19,add_to_cart,Home Goods,NaN
3,019ede3d-c48e-7eb2-9513-eb565e9a75e2,019ede3dc26074528245befb32fb1adf,2023-03-26 16:42:40,view_item,Electronics,NaN
4,019ede3d-c48e-7eb2-9513-eb6b6c26c379,019ede3dc26074528245bf0995bd0f77,2023-05-11 00:14:25,view_item,Electronics,NaN
...,...,...,...,...,...,...
51454,019ede3d-c736-7962-8dac-286f52f23e33,019ede3dc26272f3802b7253fbfcf376,2023-05-27 02:52:39,begin_checkout,NaN,NaN
51455,019ede3d-c736-7962-8dac-28714a5fde30,019ede3dc26272f3802b7261c0debe96,2023-05-24 08:03:19,view_item,Apparel,NaN
51456,019ede3d-c736-7962-8dac-288179b90708,019ede3dc26272f3802b7261c0debe96,2023-05-24 08:03:29,drop_off,Apparel,ERR_SESSION_TIMEOUT
51457,019ede3d-c736-7962-8dac-2892bd6685b1,019ede3dc26272f3802b727cb28fcae1,2023-05-21 10:40:33,view_item,Apparel,NaN
51458,019ede3d-c736-7962-8dac-28a6fa0217a0,019ede3dc26272f3802b727cb28fcae1,2023-05-21 10:40:35,view_item,Apparel,NaN

In [5]:
test_orders_df = generate_orders(df_events=test_events_df, df_sessions=test_sessions_df, rng=rng)
display(test_orders_df)

Generating 1493 orders for purchases events

,order_id,session_id,user_id,order_timestamp,payment_methods
0,019ede3dc777769292993b229130787a,019ede3dc26074528245bf418f89eec2,019ede3dc1057912a76c007e98b934f1,2023-07-30 05:22:23,COD
1,019ede3dc777769292993b3022c578aa,019ede3dc26074528245bf8e713fc736,019ede3dc1057912a76c0094e4e46d86,2023-03-01 20:05:14,Credit Card
2,019ede3dc777769292993b49d846b83c,019ede3dc26074528245bfaf77969bee,019ede3dc1057912a76c00af01950740,2023-12-08 04:20:44,Maya
3,019ede3dc777769292993b53b8b2ab49,019ede3dc26074528245bfdfa03a59a5,019ede3dc1057912a76c00d9838ebe9d,2023-12-02 19:44:24,COD
4,019ede3dc777769292993b64e1ad31d7,019ede3dc26074528245c21613fada90,019ede3dc1057912a76c01d9fcc35ff0,2023-12-05 16:43:45,COD
...,...,...,...,...,...
1488,019ede3dc7787e5182851936d2ac92c5,019ede3dc26272f3802b6f9c1583f844,019ede3dc10775209a95e8fbd0284499,2023-01-30 04:38:34,Maya
1489,019ede3dc7787e51828519416b000d6f,019ede3dc26272f3802b70e4bb38f96a,019ede3dc10775209a95e9b18f54f391,2023-12-28 13:20:19,Maya
1490,019ede3dc7787e518285195683511228,019ede3dc26272f3802b713baefefcca,019ede3dc10775209a95e9e03cb5f49f,2023-02-01 12:40:40,Credit Card
1491,019ede3dc7787e5182851967daa98d43,019ede3dc26272f3802b71809d40a803,019ede3dc10775209a95ea25c6fa85fd,2023-01-12 17:03:13,Bank Transfer
1492,019ede3dc7787e51828519769ad05b65,019ede3dc26272f3802b719c0fd182c4,019ede3dc10775209a95ea25c6fa85fd,2023-06-16 08:55:49,GCash

In [6]:
test_order_items_df = generate_order_items(df_orders=test_orders_df, df_users=test_users_df, rng=rng)
display(test_order_items_df)

Generating order items for 1493 orders
order items table generated!

,order_item_id,order_id,product_category,item_price,quantity,discount_percentage
0,019ede3dc7887640841574dbdd51bdc6,019ede3dc777769292993b229130787a,Apparel,47.48,2,0.00
1,019ede3dc7887640841574edf6ab7120,019ede3dc777769292993b229130787a,Electronics,232.18,1,0.10
2,019ede3dc7887640841574fa70d3472f,019ede3dc777769292993b3022c578aa,Electronics,268.77,1,0.00
3,019ede3dc78876408415750821bbb2ab,019ede3dc777769292993b49d846b83c,Home Goods,9710.00,1,0.15
4,019ede3dc788764084157512e8fbb41e,019ede3dc777769292993b49d846b83c,Electronics,259.44,1,0.00
...,...,...,...,...,...,...
2764,019ede3dc78876408416219bb807151d,019ede3dc7787e51828519416b000d6f,Home Goods,74.96,1,0.00
2765,019ede3dc7887640841621ac34f62c78,019ede3dc7787e518285195683511228,Electronics,328.48,1,0.00
2766,019ede3dc7887640841621bf86614e93,019ede3dc7787e5182851967daa98d43,Electronics,227.55,1,0.20
2767,019ede3dc7887640841621c14d36fa6c,019ede3dc7787e51828519769ad05b65,Home Goods,122.32,1,0.00
2768,019ede3dc7887640841621d402a783fd,019ede3dc7787e51828519769ad05b65,Apparel,79.54,1,0.00